[package]
name = "bilge-defmt"
version = "0.2.1"
edition = "2024"
authors = ["Johannes Cornelis Draaijer <jcdra1@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A derive macro that implements defmt::Format for your bilge structs"
homepage = "https://github.com/datdenkikniet/bilge-defmt"
keywords = ["bilge", "defmt"]
categories = ["embedded", "no-std"]
readme = "README.md"

[dependencies]
bilge-defmt-impl = { version = "0.2.0", path = "./bilge-defmt-impl" }
defmt = "1"
arbitrary-int = { version = "2", features = [ "defmt" ]}
