[package]
name = "bilge-defmt-impl"
version = "0.2.2"
edition = "2024"
authors = ["Johannes Cornelis Draaijer <jcdra1@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Proc-macro implementation for bilge-defmt. See bilge-defmt for more information"
homepage = "https://github.com/datdenkikniet/bilge-defmt"
keywords = ["bilge", "defmt"]
categories = ["embedded", "no-std"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
# WARN: do _not_ activate `syn2` or `syn3` features: they are mutually
# exclusive. See: https://github.com/ModProg/manyhow/issues/28
manyhow = { version = "0.13.0", default-features = false, features = [ "macros" ] }
