[package]
name = "bilge-defmt-impl"
version = "0.2.0"
edition = "2024"
authors = ["Johannes Cornelis Draaijer <jcdra1@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Proc-macro implementation for bilge-defmt. See bilge-defmt for more information"
homepage = "https://github.com/datdenkikniet/bilge-defmt"
keywords = ["bilge", "defmt"]
categories = ["embedded", "no-std"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
manyhow = "0.13.0"
